### ISSUE TITLE
Favicon doesn't update after waking from sleep

### ISSUE THREAD

**Issue by MistriHD** [nicolaschan/bell#13] opened 2017-10-19 18:52 UTC
If I closed the computer lid when the favicon was red, and then open it again when it should be green, it stays red but everything else still works.

**Comment by nicolaschan** [comment] 2017-10-21 00:08
Confirmed in Chrome on Windows. This is because network is disconnected while the computer sleeps, so when it tries to load the new favicon, it sees that it is missing and does not attempt to reload.

This has been fixed by refreshing the icon every 10 seconds and will be available in the next release.

**Closed by nicolaschan** 2017-10-21 00:08 UTC
